spring.application.name=back

spring.jackson.default-property-inclusion=always

jwt.secret=PZlIrKUqP6BS3jJzhYpEVvsOmPvzm4qU5EU99PoQ48c=
jwt.expiration = 86400000
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=Bar_Livre; integratedSecurity=false;encrypt=false;trustServerCertificate=false
spring.datasource.username=sa
spring.datasource.password=Pa$$w0rd
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mvc.pathmatch.matching-strategy=ant_path_matcher
