spring.application.name=back

spring.jackson.default-property-inclusion=always

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=Bar_Livre; integratedSecurity=false;encrypt=false;trustServerCertificate=false
spring.datasource.username=sa
spring.datasource.password=Pa$$w0rd

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

