spring.application.name=back
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=Bar_Livre;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Pa$$w0rd
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true