### Variables
@baseUrl = http://localhost:8080
@livreIsbn = ISBN024
@userId = 1

### GET - Récupérer tous les emprunts (LIBRARIAN)
GET {{baseUrl}}/api/loans

### GET - Récupérer un emprunt par ID
GET {{baseUrl}}/api/loans/6

### GET - Récupérer mes emprunts
GET {{baseUrl}}/api/loans/my

### POST - Emprunter un livre
POST {{baseUrl}}/api/loans
Content-Type: application/json

{
  "userId" : "{{userId}}",
  "livreIsbn": "{{livreIsbn}}"
}

### PUT - Retourner un livre
PUT {{baseUrl}}/api/loans/11/return

